# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6d7fd1a65275c79d0e3ea182425268143702d37b136b990fbe42bdf72e41e55c3b959995e07e9af6ac4ebd9b582f5c7994ebdfaf6980c2defa94249e2a3ace67

test:
  secret_key_base: c9024cd2a80384fdcf56d9b24d1eae5d0b047253a429c6da225343a9e47638469c06a689edd2e572c777994ef5b8f3bb299e36e47496874a72dcbc5bcca542da

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
